baseURL = 'https://example.org/'
# languageCode = 'en-us'
languageCode = 'de-DE'
title = 'Introduktion till datorer 2024'

# Do not set theme here when using modules. 

# theme = 'hugo-theme-relearn'

# theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

# theme = "PaperMod"

# Modules on the bottom will get loaded first, so keep anything you don’t want
# overridden higher up in the module chain. All conflicting files during module
# import will use the last file loaded. 

[module]
    [[module.mounts]]
        source = "2024/content"
        target = "content"
    [[module.mounts]]
        source = "2024/static/images"
        target = "static/images"
    [[module.mounts]]
        source = "2024/static/terminal"
        target = "static/terminal"

[params]
    year = 2024
